### ISSUE TITLE
settingForm报错Cannot read properties of null (reading 'workbench')

### ISSUE THREAD

**Issue by osCaiwei** [trionesdev/triones-designable#12]
代码如下  我按照demo编辑了如下代码 有时候运行正常 有时候就会报错找不到workbench 想请问一下有可能什么原因导致的  之前报错我通过更新包版本解决过一次  但这次我看包都是最新的 
![image](https://github.com/user-attachments/assets/a3d3a65f-fd36-4d43-ae2b-a60ef61b706b)

**Comment by osCaiwei** [comment]
报错是settingForm组件

**Comment by osCaiwei** [comment]
![image](https://github.com/user-attachments/assets/8bbb448a-89d5-408a-ab7f-9bc8e2820f64)
我通过注释该组件能正常运行

**Comment by fengxiaotx** [comment]
你好 这个是因为pnpm对es版本要求比较高的原因 另外pnpm 在做monorepo的时候不太友好，当然 也可能是我不得其法。目前已经做了修复，你可以再尝试下最新的版本 或者用yarn来试试

**Comment by osCaiwei** [comment]
谢谢答复 这问题我找到了 是因为antd版本过低导致的 更新到5.13以上就解决了
