### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by contorlxys** [trionesdev/triones-designable#2]
Module not found: Error: Can't resolve '@trionesdev/designable-core' in 'E:\Test\lowCode\triones-designable-develop\examples\basic\src'

**Comment by Gzx97** [comment]
请在项目根目录先执行一遍 `yarn` 保证所有依赖包已经安装；
然后请先手动执行 packages 文件夹下的  core、flow、react、react-settings-form、shared应用package.json下的dev命令。
同理手动执行初始化一遍formily文件夹下的所有相关的应用的package.json下的dev命令。
如果还有问题请贴出具体环境信息。
