### ISSUE TITLE
请问一下，这个表单设计器的样式文件需要单独引入么

### ISSUE THREAD

**Issue by york-chen** [trionesdev/triones-designable#7]
我把项目跑起来了 发觉样式不对，就自己翻源码 把样式挨着 挨着的引入了，是我使用的姿势不对吗

**Comment by fengxiaotx** [comment]
不需要的 里面用的是 css-in-js 。样式不对的话 你看下 预览页面 是不是差不多

**Comment by york-chen** [comment]
感谢大佬，我把umi的缓存清除了之后，现在确实正常了，

**Comment by york-chen** [comment]
有个问题想请教一下，把这个设计器从antv4升级到了v5 schema那些属性有什么变化吗，因为我记得有些表单组件的属性名字v5是变化了的

**Comment by fengxiaotx** [comment]
组件基本没啥变化 有的话 就修复 其实 组件 都是可以自己定义的

**Comment by york-chen** [comment]
哎  我现在有个需求，想再管理后台拖动之后生成表单模板 在pc端 和移动端都能用，这咋搞额，react方面好像没有这样的库

**Comment by fengxiaotx** [comment]
不要做复杂布局  就是那种一行一个组件 复杂布局 肯定满足不了的
